# Generated by Django 5.0.1 on 2026-03-01 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0002_initial'),
        ('trabajos', '0007_ofertatrabajo_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='trabajos.trabajo'),
        ),
    ]
