# Generated by Django 5.0.1 on 2026-04-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensajes',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='mensajes',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensajes',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('calificacion', 'Calificación'), ('imagen', 'Imagen'), ('archivo', 'Archivo')], default='texto', max_length=20),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='texto',
            field=models.TextField(blank=True),
        ),
        migrations.AlterModelTable(
            name='mensajes',
            table=None,
        ),
    ]
