# Generated by Django 5.0.1 on 2026-03-01 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0003_recurso_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='mensajeria.chat'),
        ),
    ]
