# Generated by Django 5.0.1 on 2026-04-20 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0003_alter_mensajes_options_mensajes_metadata_and_more'),
        ('trabajos', '0003_trabajo_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='trabajos.trabajo'),
        ),
    ]
