# Generated by Django 5.0.1 on 2026-04-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0004_mensajes_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='calificado',
            field=models.BooleanField(default=False),
        ),
    ]
