# Generated by Django 5.0.1 on 2026-04-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones',
            name='leida',
            field=models.BooleanField(default=False),
        ),
    ]
