# Generated by Django 5.0.1 on 2026-03-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoPagoCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado en')),
                ('mp_customer_id', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Customer MercadoPago',
                'verbose_name_plural': 'Customers MercadoPago',
                'db_table': 'mercadopago_customer',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado en')),
                ('tipo', models.CharField(choices=[('orden', 'Orden de productos'), ('trabajo', 'Trabajo/Servicio')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comision_plataforma', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_vendedor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mp_preference_id', models.CharField(blank=True, default='', max_length=255)),
                ('mp_order_id', models.CharField(blank=True, default='', max_length=255)),
                ('mp_payment_id', models.CharField(blank=True, default='', max_length=255)),
                ('mp_status', models.CharField(blank=True, default='', max_length=50)),
                ('mp_status_detail', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en_proceso', 'En proceso'), ('devuelto', 'Devuelto'), ('cancelado', 'Cancelado'), ('liberado', 'Liberado')], default='pendiente', max_length=20)),
                ('liberado_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado en')),
                ('mp_card_id', models.CharField(max_length=255)),
                ('last_four', models.CharField(max_length=4)),
                ('brand', models.CharField(blank=True, default='', max_length=50)),
                ('expiration_month', models.IntegerField()),
                ('expiration_year', models.IntegerField()),
                ('payment_method_id', models.CharField(blank=True, default='', max_length=50)),
                ('payment_type', models.CharField(blank=True, default='credit_card', max_length=30)),
                ('issuer_id', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'db_table': 'tarjeta',
            },
        ),
    ]
