# Generated by Django 5.0.1 on 2026-03-16 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_mercadopagovendedor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MercadoPagoVendedor',
        ),
    ]
