# Generated by Django 5.0.1 on 2026-09-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesion', '0003_seed_vendedor_profesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='aprobada', max_length=20),
        ),
    ]
