# Generated by Django 5.0.1 on 2026-01-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizacion',
            name='isPrimary',
            field=models.BooleanField(default=False),
        ),
    ]
