# Generated by Django 5.0.1 on 2026-02-19 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizacion', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='localizacion',
            index=models.Index(fields=['latitud'], name='idx_localizacion_latitud'),
        ),
        migrations.AddIndex(
            model_name='localizacion',
            index=models.Index(fields=['longitud'], name='idx_localizacion_longitud'),
        ),
        migrations.AddIndex(
            model_name='localizacion',
            index=models.Index(fields=['latitud', 'longitud'], name='idx_localizacion_geo'),
        ),
    ]
