# Generated by Django 5.0.1 on 2026-03-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado en')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'calificacion',
            },
        ),
        migrations.CreateModel(
            name='OfertaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado en')),
                ('precio_ofertado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_estimado', models.IntegerField(help_text='Tiempo estimado en minutos')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
            ],
            options={
                'verbose_name': 'Oferta de Trabajo',
                'verbose_name_plural': 'Ofertas de Trabajo',
                'db_table': 'oferta_trabajo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado en')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('pendiente_urgente', 'Pendiente Urgente'), ('aceptado', 'Aceptado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('esUrgente', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('precio_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comentario_cliente', models.TextField(blank=True, null=True)),
                ('cancelado_cliente', models.BooleanField(default=False)),
                ('es_domicilio_profesional', models.BooleanField(default=False)),
                ('radio_busqueda_km', models.DecimalField(blank=True, decimal_places=2, help_text='Radio de búsqueda para trabajos urgentes', max_digits=5, null=True)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('app', 'Pago en app')], max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
                'db_table': 'trabajo',
            },
        ),
        migrations.CreateModel(
            name='TrabajoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado en')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Trabajo Servicio',
                'verbose_name_plural': 'Trabajo Servicios',
                'db_table': 'trabajo_servicio',
            },
        ),
    ]
