# Generated by Django 5.0.1 on 2026-01-31 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_initial'),
        ('trabajos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos', to='servicios.servicio'),
        ),
    ]
