# Generated by Django 5.0.1 on 2026-03-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='currency',
            field=models.CharField(blank=True, choices=[('ARS', 'Peso Argentino'), ('BRL', 'Real Brasileño'), ('CLP', 'Peso Chileno'), ('COP', 'Peso Colombiano'), ('MXN', 'Peso Mexicano'), ('PEN', 'Sol Peruano'), ('UYU', 'Peso Uruguayo'), ('BOB', 'Boliviano'), ('PYG', 'Guaraní Paraguayo'), ('VES', 'Bolívar Venezolano'), ('CRC', 'Colón Costarricense'), ('DOP', 'Peso Dominicano'), ('GTQ', 'Quetzal Guatemalteco'), ('HNL', 'Lempira Hondureño'), ('NIO', 'Córdoba Nicaragüense'), ('PAB', 'Balboa Panameño'), ('USD', 'Dólar Estadounidense')], max_length=3, null=True),
        ),
    ]
