# Generated by Django 5.0.1 on 2026-02-01 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilidad', '0003_remove_disponibilidad_fecha_yyyy_mm_dd_and_more'),
        ('servicios', '0002_initial'),
        ('trabajos', '0003_alter_trabajo_servicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='subcategoria_id',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='trabajo_id',
        ),
        migrations.AddField(
            model_name='trabajo',
            name='disponibilidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos', to='disponibilidad.disponibilidad'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='esUrgente',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TrabajoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado en')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajo_servicios', to='trabajos.trabajo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Trabajo Servicio',
                'verbose_name_plural': 'Trabajo Servicios',
                'db_table': 'trabajo_servicio',
            },
        ),
        migrations.DeleteModel(
            name='Estados',
        ),
    ]
