# Generated by Django 5.0.1 on 2026-02-05 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizacion', '0002_initial'),
        ('trabajos', '0004_remove_trabajo_categoria_remove_trabajo_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='es_domicilio_profesional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='localizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos', to='localizacion.localizacion'),
        ),
    ]
