# Generated by Django 5.0.1 on 2026-02-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0006_trabajos_urgentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertatrabajo',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
