# Generated by Django 5.0.1 on 2026-03-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0007_ofertatrabajo_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('app', 'Pago en app')], max_length=20, null=True),
        ),
    ]
