# Generated by Django 5.0.1 on 2026-08-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0008_ofertatrabajo_motivo_rechazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='phoneNumberInvitedUser',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
