# Generated by Django 5.0.1 on 2026-03-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0008_trabajo_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('app', 'Pago en app'), ('mercadopago', 'MercadoPago')], max_length=20, null=True),
        ),
    ]
