# Generated by Django 5.0.1 on 2026-09-08 23:31

import uuid
from django.db import migrations, models


def poblar_tokens(apps, schema_editor):
    """Asigna un UUID único a cada trabajo existente antes de aplicar el unique.

    El AddField aplica el mismo default a todas las filas, así que hay que
    regenerar el token por cada fila (no solo las nulas).
    """
    Trabajo = apps.get_model('trabajos', 'Trabajo')
    for trabajo in Trabajo.objects.all().only('id'):
        trabajo.token_confirmacion = uuid.uuid4()
        trabajo.save(update_fields=['token_confirmacion'])


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0009_trabajo_phonenumberinviteduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='recordatorio_12h_enviado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='recordatorio_1h_enviado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # 1) columna nullable sin unique
        migrations.AddField(
            model_name='trabajo',
            name='token_confirmacion',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        # 2) poblar con valores únicos por fila
        migrations.RunPython(poblar_tokens, migrations.RunPython.noop),
        # 3) aplicar el unique definitivo
        migrations.AlterField(
            model_name='trabajo',
            name='token_confirmacion',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
