# Generated by Django 5.0.1 on 2026-01-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado en')),
                ('nombre', models.CharField(default='', max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('divisa', models.CharField(default='ARS', max_length=10)),
                ('tiempo', models.IntegerField(help_text='Tiempo estimado en minutos')),
                ('notas', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'usuario_servicios',
            },
        ),
    ]
