# Generated by Django 5.0.1 on 2026-01-28 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesion', '0002_initial'),
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicio',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='servicio',
            unique_together={('usuario', 'profesion', 'nombre')},
        ),
    ]
