# Generated by Django 5.0.1 on 2026-03-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='foto',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
