# Generated by Django 5.0.1 on 2026-01-23 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizacion', '0001_initial'),
        ('usuario_localizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariolocalizacion',
            name='es_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuariolocalizacion',
            name='localizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='localizacion.localizacion'),
        ),
    ]
