# Generated by Django 5.0.1 on 2026-03-16 16:03

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('defaultMessageReservation', models.CharField(default='Gracias por reservar!. En breve nos pondremos en contacto contigo', max_length=1000)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('foto_url', models.URLField(blank=True, max_length=500, null=True)),
                ('rounded_foto_url', models.URLField(blank=True, max_length=500, null=True)),
                ('trabajo_domicilio', models.BooleanField(default=False)),
                ('trabajo_local', models.BooleanField(default=False)),
                ('is_owner_empresa', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('rango_mapa_km', models.DecimalField(decimal_places=2, default=10.0, help_text='Radio de búsqueda en kilómetros', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_configured', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0)),
                ('cant_calif', models.IntegerField(default=0)),
                ('auto_aprobacion_trabajos', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='rol.rol')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nombre'], name='usuario_nombre_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=django.contrib.postgres.indexes.GinIndex(fields=['apellido'], name='usuario_apellido_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
