# Generated by Django 5.0.1 on 2026-02-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='auto_aprobacion_trabajos',
            field=models.BooleanField(default=False),
        ),
    ]
