# Generated by Django 5.0.1 on 2026-01-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rango_mapa_km',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Radio de búsqueda en kilómetros', max_digits=5),
        ),
    ]
