# Generated by Django 5.0.1 on 2026-02-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_auto_aprobacion_trabajos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rounded_foto_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
