# Generated by Django 5.0.1 on 2026-01-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_rango_mapa_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_configured',
            field=models.BooleanField(default=False),
        ),
    ]
