# Generated by Django 5.0.1 on 2026-03-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_rounded_foto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cant_calif',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
