# Generated by Django 5.0.1 on 2026-03-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_cant_calif_usuario_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='defaultMessageReservation',
            field=models.CharField(default='Gracias por reservar!. En breve nos pondremos en contacto contigo', max_length=1000),
        ),
    ]
