# Generated by Django 5.0.1 on 2026-09-21 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_backfill_rounded_foto_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('resultados_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='busquedas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historial_busqueda',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['query'], name='idx_historial_busqueda_query')],
            },
        ),
    ]
