# Generated by Django 5.0.1 on 2026-09-21 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_historialbusqueda'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='invitado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario profesional cuyo link de invitación se usó al registrarse.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitados', to=settings.AUTH_USER_MODEL),
        ),
    ]
