# Generated by Django 5.0.1 on 2026-09-21 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_usuario_invitado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visita_perfil',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profesional', 'created_at'], name='idx_visita_perfil_prof_fecha')],
            },
        ),
    ]
