# Generated by Django 5.0.1 on 2026-03-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carritos', '0002_add_is_deleted_to_carritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='comision_plataforma',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='pago_status',
            field=models.CharField(blank=True, default='', help_text='Estado del pago MP', max_length=20),
        ),
        migrations.AlterField(
            model_name='orden',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('app', 'Pago en app'), ('mercadopago', 'MercadoPago')], max_length=20),
        ),
    ]
