# Generated by Django 5.0.1 on 2026-03-16 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carritos', '0003_orden_comision_plataforma_orden_pago_status_and_more'),
        ('empresas', '0010_empresa_acepta_efectivo_empresa_acepta_tarjeta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carrito',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='carrito',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('usuario', 'empresa'), name='unique_carrito_activo_por_usuario_empresa'),
        ),
    ]
