# Generated by Django 5.0.1 on 2026-07-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carritos', '0003_orden_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
