# Generated by Django 5.0.1 on 2026-03-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='cantidad_jobs',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='subscripcion',
            name='jobs_restantes',
            field=models.IntegerField(default=0),
        ),
    ]
