# Generated by Django 5.0.1 on 2026-01-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='plan_id_stripe',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='usuario',
        ),
        migrations.AddField(
            model_name='plan',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='appstore_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='plan',
            name='google_play_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='nombre',
            field=models.CharField(default='Plan Básico', max_length=200),
        ),
        migrations.AddField(
            model_name='plan',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='cantidad_personas',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plan',
            name='caracteristicas',
            field=models.JSONField(default=list),
        ),
    ]
