# Generated by Django 5.0.1 on 2026-09-21 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0005_plan_tiene_landing_page'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado en')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('duracion', models.DurationField(help_text='Tiempo que la campaña acepta nuevos registros gratis.')),
                ('dias_gratis', models.PositiveIntegerField(help_text='Duración de la suscripción gratis otorgada.')),
                ('precio_tachado', models.DecimalField(decimal_places=2, default=5.99, max_digits=10)),
                ('cupo_usuarios', models.PositiveIntegerField(blank=True, help_text='Cantidad máxima de usuarios para el mensaje "primeros X clientes". Vacío = sin límite.', null=True)),
                ('activa', models.BooleanField(default=True, help_text='Toggle manual del admin.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Campaña de marketing',
                'verbose_name_plural': 'Campañas de marketing',
                'db_table': 'campana_marketing',
            },
        ),
        migrations.AddField(
            model_name='subscripcion',
            name='campana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscripciones', to='suscripciones.campanamarketing'),
        ),
    ]
