# Generated by Django 5.0.1 on 2026-09-22 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0006_campanamarketing_subscripcion_campana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanamarketing',
            name='precio_tachado',
        ),
        migrations.AddField(
            model_name='campanamarketing',
            name='mensaje_promocional',
            field=models.TextField(blank=True, default='', help_text='Texto libre que se muestra junto al plan en /planes mientras la campaña esté vigente.'),
        ),
        migrations.AddField(
            model_name='campanamarketing',
            name='plan',
            field=models.ForeignKey(default=1, help_text='Plan que se regala mientras la campaña esté vigente.', on_delete=django.db.models.deletion.PROTECT, related_name='campanas', to='suscripciones.plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='recomendado',
            field=models.BooleanField(default=False, help_text='Se muestra preseleccionado y destacado como "Recomendado" en /planes.'),
        ),
    ]
