# Generated by Django 5.0.1 on 2026-09-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0008_remove_plan_idx_plan_rank_remove_plan_cantidad_jobs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='badge_mapa_url',
            field=models.URLField(blank=True, help_text='SVG o PNG (transparente) del pin de mapa para este plan: un agujero circular transparente en el centro es donde se compone la foto del usuario.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='user_badge_url',
            field=models.URLField(blank=True, help_text='SVG o PNG del ícono/insignia que se muestra sobre la foto del usuario (buscador, detalle de perfil desde el mapa, perfil propio) para este plan.', max_length=500, null=True),
        ),
    ]
