# Generated by Django 5.0.1 on 2026-09-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0009_plan_badge_mapa_url_plan_user_badge_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='color',
            field=models.CharField(blank=True, help_text='Color hex (ej. #F59E0B) usado en el badge/anillo del plan. Vacío = gris por defecto.', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='slogan',
            field=models.CharField(blank=True, default='', help_text='Texto corto del badge del plan (ej. "Pro"). Vacío = usa el nombre del plan.', max_length=40),
        ),
    ]
