# Generated by Django 5.0.1 on 2026-07-13 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(db_index=True, max_length=32)),
                ('direccion', models.CharField(choices=[('entrante', 'Entrante'), ('saliente', 'Saliente')], max_length=10)),
                ('tipo', models.CharField(default='text', max_length=20)),
                ('wa_message_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('leido', 'Leído'), ('fallido', 'Fallido'), ('recibido', 'Recibido')], default='pendiente', max_length=15)),
                ('texto', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_whatsapp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje de WhatsApp',
                'verbose_name_plural': 'Mensajes de WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
    ]
