# Generated by Django 5.0.1 on 2026-05-06 00:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado en')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo electrónico')),
                ('likelihood', models.CharField(choices=[('definite', 'Definitivamente'), ('likely', 'Probablemente'), ('maybe', 'Tal vez'), ('no', 'No')], max_length=20, verbose_name='Intención de uso')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('pro', 'Profesional'), ('both', 'Ambos')], max_length=20, verbose_name='Perfil')),
                ('willing_to_pay', models.BooleanField(blank=True, null=True, verbose_name='Dispuesto a pagar')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado en')),
                ('source', models.CharField(default='landing_page', max_length=60, verbose_name='Origen')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Respuesta de encuesta',
                'verbose_name_plural': 'Respuestas de encuesta',
                'db_table': 'survey_responses',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(condition=models.Q(('email__isnull', False)), fields=['email'], name='idx_sr_email'), models.Index(fields=['role'], name='idx_sr_role'), models.Index(fields=['likelihood'], name='idx_sr_likelihood'), models.Index(fields=['-submitted_at'], name='idx_sr_submitted_at')],
            },
        ),
    ]
