# Generated by Django 5.0.1 on 2026-01-31 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='updated_by',
        ),
    ]
