# Generated by Django 5.0.1 on 2026-01-28 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_initial'),
        ('localizacion', '0002_localizacion_isprimary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='localizacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='localizacion.localizacion'),
        ),
        migrations.DeleteModel(
            name='Localizacion',
        ),
    ]
