# Generated by Django 5.0.1 on 2026-01-31 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_remove_servicios_created_by_and_more'),
        ('trabajos', '0003_alter_trabajo_servicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicios',
        ),
    ]
