# Generated by Django 5.0.1 on 2026-02-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_empresa_vende_productos_empresa_vende_servicios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='agotado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['agotado', '-created_at'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
