# Generated by Django 5.0.1 on 2026-03-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_empresa_vende_productos_empresa_vende_servicios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproducto',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='categoriaproducto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en'),
        ),
    ]
