# Generated by Django 5.0.1 on 2026-03-14 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_categoriaproducto_is_deleted_producto_is_deleted_and_more'),
        ('empresas', '0006_producto_agotado'),
    ]

    operations = [
    ]
