# Generated by Django 5.0.1 on 2026-02-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_producto_agotado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
