# Generated by Django 5.0.1 on 2026-03-14 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_merge_20260314_1845'),
        ('empresas', '0007_producto_foto'),
    ]

    operations = [
    ]
