# Generated by Django 5.0.1 on 2026-03-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_alter_producto_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='acepta_efectivo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='acepta_tarjeta',
            field=models.BooleanField(default=True),
        ),
    ]
