# Generated by Django 5.0.1 on 2026-03-16 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado en')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('bloqueado', 'Bloqueado')], default='disponible', max_length=20)),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('trabajo', 'Trabajo'), ('empresa', 'Empresa'), ('sistema', 'Sistema')], default='manual', max_length=20)),
            ],
            options={
                'verbose_name': 'Disponibilidad',
                'verbose_name_plural': 'Disponibilidades',
                'db_table': 'disponibilidad',
            },
        ),
    ]
