# Generated by Django 5.0.1 on 2026-01-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado en')),
                ('user_id', models.IntegerField()),
                ('fecha_yyyy_mm_dd', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo_disponible', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_bloqueado', models.CharField(blank=True, max_length=50, null=True)),
                ('origen_manual', models.BooleanField(default=False)),
                ('origen_trabajo', models.BooleanField(default=False)),
                ('origen_empresa', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Disponibilidad',
                'verbose_name_plural': 'Disponibilidades',
                'db_table': 'disponibilidad',
            },
        ),
    ]
