# Generated by Django 5.0.1 on 2026-01-31 15:16

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilidad', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidad',
            name='fecha_yyyy_mm_dd',
        ),
        migrations.RemoveField(
            model_name='disponibilidad',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='disponibilidad',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='disponibilidad',
            name='origen_empresa',
        ),
        migrations.RemoveField(
            model_name='disponibilidad',
            name='origen_manual',
        ),
        migrations.RemoveField(
            model_name='disponibilidad',
            name='origen_trabajo',
        ),
        migrations.RemoveField(
            model_name='disponibilidad',
            name='tipo_bloqueado',
        ),
        migrations.RemoveField(
            model_name='disponibilidad',
            name='tipo_disponible',
        ),
        migrations.RemoveField(
            model_name='disponibilidad',
            name='user_id',
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='fecha_fin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='origen',
            field=models.CharField(choices=[('manual', 'Manual'), ('trabajo', 'Trabajo'), ('empresa', 'Empresa'), ('sistema', 'Sistema')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='tipo',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('bloqueado', 'Bloqueado')], default='disponible', max_length=20),
        ),
        migrations.AddIndex(
            model_name='disponibilidad',
            index=models.Index(fields=['usuario', 'fecha_inicio', 'fecha_fin'], name='disponibili_usuario_c5da37_idx'),
        ),
    ]
